server:
  port: 8085

spring:
  application:
    name: internet-banking-utility-payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/banking_core_utility_payment_service
    username: root
    password: changeme
  jpa:
    hibernate:
      ddl-auto: none

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

info:
  app:
    name: ${spring.application.name}
